version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./app-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_DB: ecommerce
  django:
    build: ./Ecommerce
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./Ecommerce:/app/Ecommerce
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ecommerce
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=ecommerce
    depends_on:
      - db
  frontend:
    build: ./ecommerce-frontend
    command: ["npm", "start"]
    volumes:
      - ./ecommerce-frontend:/app/ecommerce-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node-modules: